services:
  _defaults:
    autowire: true
    autoconfigure: true

  Creative\DbI18nBundle\:
    resource: '../../../src'
    exclude: '../../../src/{Entity,Resources}'

  translation.loader.db:
    class: Creative\DbI18nBundle\Loader\DbLoader
    public: '%kernel.debug%'
    arguments:
      - '@service_container'
      - '@doctrine'
    tags:
      - { name: translation.loader, alias: db }

  Creative\DbI18nBundle\Interfaces\TranslationRepositoryInterface:
    class: Creative\DbI18nBundle\Repository\TranslationRepository
    tags:
      - { name: doctrine.repository_service }

  Creative\DbI18nBundle\Command\MigrateToDatabaseCommand:
    arguments:
      - '@service_container'
      - '@translator.default'
      - '@doctrine'
    tags: [ console.command ]
